logs:
  - name: root
    level: info
    formatter: "%d%T%m%n"
    appenders:
      - type: FileLogAppender
        file: root.txt
      - type: StdLogAppender
  - name: system
    level: debug
    formatter: "%d%T%c%T{%p}%T%m%n"
    appenders:
      - type: FileLogAppender
        file: root.txt
        formatter: "%d%T%c%T{%p}%T%m%n"
      - type: StdLogAppender
